### ISSUE TITLE
Please take care in using sp

### ISSUE THREAD

**Issue by rsbivand** [SydneyBioX/MoleculeExperiment#1]
Please read all of https://r-spatial.org/r/2023/05/15/evolution4.html and the previous reports. The `sp` package is really for geographical data, and has largely been superceded by `sf` (S3) and `terra` (S4 but only pointers to objects in memory). My guess is that if "spatial" cluster packages in BioConductor need classes, you'd need either to borrow from what geo-spatial CRAN packages are doing, or look to start an R7 process to succeed `sp`. https://github.com/SydneyBioX/MoleculeExperiment/blob/8af3918aaa8b5031ab94a14f33e0799aabc72bb7/R/countMolecules.R#L243 looks very vulnerable, as `sp` has used `rgeos`(to be archived in October 2023) for some `over` methods. Your `NAMESPACE` file does not import anything from `sp`.

**Comment by shazanfar** [comment]
Hi @rsbivand , thank you for bringing these upcoming changes to `sp` to our attention. I'm pleased that we have already implemented a new faster function based on `terra`, and the `sp` dependency belongs to the function that has already been superceded - we had kept this for internal development and checking. Therefore, we have been able to straightforwardly remove the dependency on `sp` by just removing the function in question completely, and just use `terra`. Thank you!
